---
- name: 获取 machine-id
  slurp: src=/etc/machine-id
  register: machine_id

- name: 显示 machine id
  debug:
    msg: "{{ inventory_hostname }} machine id: {{ machine_id.content | b64decode | trim }}"

- name: 创建目录
  file: path={{ item }} state=directory
  with_items:
  - /usr/local/scripts
  - "{{ workspace }}"
  - /var/pi-robot

- name: 上传配置文件
  template: src=config.yaml dest=/var/pi-robot/config.yaml

- name: 上传并解压机器人安装包
  unarchive: src=robot.tar.gz dest={{ workspace }}

- name: 上传打量脚本
  template: src=curl.sh.j2 dest=/usr/local/scripts/curl.sh

- name: 上传机器人流量监控脚本
  template: src=robot_flow.sh dest={{ workspace }}/robot_flow.sh

- name: 上传修改网卡参数脚本
  template: src=select_net_card.sh dest={{ workspace }}/select_net_card.sh

- name: 上传清理脚本
  template: src=clean.sh dest={{ workspace }}/clean.sh

- name: 清理进程
  shell: "/bin/bash {{ workspace }}/clean.sh"

- name: 修改脚本参数
  shell: "/bin/bash {{ workspace }}/select_net_card.sh"

- name: 启动打量机器人
  shell: "nohup /bin/bash {{ workspace }}/start.sh > {{ workspace }}/start_robot.log 2>&1 &"

- name: 启动流量监控脚本
  shell: "nohup /bin/bash {{ workspace }}/robot_flow.sh > {{ workspace }}/start_monitor.log 2>&1 &"

- name: 设置定时任务
  cron:
    name: "robot cron task"
    minute: "{{ ( inventory_hostname | hash | list | map('int',0,16) | sum ) % 60 }}"
    hour: "{{ (( inventory_hostname | hash | list | map('int',0,16) | sum ) % 6) + 6 }}"
    job: "/bin/bash /usr/local/scripts/curl.sh > /dev/null 2>&1"

- name: 定时任务显示
  shell: "crontab -l |grep curl.sh"
  register: crontab_list

- name: 显示定时任务
  debug: var=crontab_list verbosity=0

- name: 进程显示
  shell: "ps -ef | grep robot | grep -v grep"
  register: process_list

- name: 显示机器人相关进程
  debug:
    msg: var=process_list verbosity=0
